name: Continuous Integration
on:
  push:
    branches: [master]
  pull_request:
jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04] # macos-latest currently broken
        python: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10"] # breaks on "3.11.0-alpha.6"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
           if [ "$RUNNER_OS" == 'Linux' ]; then
             sudo apt-get install -y db-util rpm yum
           else
             brew install rpm
             sudo mkdir -p /var/lib/rpm
           fi
           pip install -r requirements-test.txt
    - name: Run unit tests
      run: pytest -v
  black:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run black
      uses: lgeiger/black-action@v1.0.1
      with:
        args: "--check ."
  pyre:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3
   - name: Setup Python
     uses: actions/setup-python@v3
   - name: Install dependencies
     run: pip install -r requirements-test.txt pyre-check==0.0.20
   - name: Run Pyre typechecking
     run: |
          pyre \
            --noninteractive \
            --source-directory dcrpm \
            --source-directory tests \
            --output text \
            --search-path "$(python -c "import site; print(site.getsitepackages()[0])")" \
            --search-path . \
            --show-parse-errors \
            check
# FIXME disable for now, the markdown docs here need lots of work
#  markdown:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#    - name: Lint Markdown
#      uses: actionshub/markdownlint@1.2.0
#    - name: Check links
#      uses: gaurav-nelson/github-action-markdown-link-check@v1
